### ISSUE TITLE
options.json

### ISSUE THREAD

**Issue by davetang** [biowdl/germline-DNA#76]
In the [documentation](https://biowdl.github.io/germline-DNA/v4.0.0/index.html), the example for `options.json` is:

```
{
  "final_workflow_outputs_dir": "/path/to/outputs",
  "use_relative_output_paths": true,
}
```

The comma after true needs to be removed or else Cromwell expects another option.

```
Exception in thread "main" cromwell.CromwellEntryPoint$$anon$2: ERROR: Unable to submit workflow to Cromwell::
Unexpected character '}' at input index 125 (line 4, position 1), expected '"':
}
^

        at cromwell.CromwellEntryPoint$.$anonfun$validOrFailSubmission$1(CromwellEntryPoint.scala:274)
        at cats.data.Validated.valueOr(Validated.scala:110)
        at cromwell.CromwellEntryPoint$.validOrFailSubmission(CromwellEntryPoint.scala:274)
        at cromwell.CromwellEntryPoint$.validateRunArguments(CromwellEntryPoint.scala:270)
        at cromwell.CromwellEntryPoint$.runSingle(CromwellEntryPoint.scala:66)
        at cromwell.CromwellApp$.runCromwell(CromwellApp.scala:14)
        at cromwell.CromwellApp$.delayedEndpoint$cromwell$CromwellApp$1(CromwellApp.scala:25)
        at cromwell.CromwellApp$delayedInit$body.apply(CromwellApp.scala:3)
        at scala.Function0.apply$mcV$sp(Function0.scala:39)
        at scala.Function0.apply$mcV$sp$(Function0.scala:39)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
        at scala.App.$anonfun$main$1$adapted(App.scala:80)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.App.main(App.scala:80)
        at scala.App.main$(App.scala:78)
        at cromwell.CromwellApp$.main(CromwellApp.scala:3)
        at cromwell.CromwellApp.main(CromwellApp.scala)
```

**Comment by JasperBoom** [comment]
Thank you for reporting this mistake!
We have updated the documentation on our development branch and will update our gh-pages soon.
